### ISSUE TITLE
Buttons are shifted

### ISSUE THREAD

**Issue by nahaivla** [duosecurity/duo_java#18]
Hi,

I'm struggling against shifted buttons, for particular version of IE it could be one of these

        <meta http-equiv="X-UA-Compatible" content="IE=9; IE=8; IE=7; IE=6; IE=edge" />

![image](https://user-images.githubusercontent.com/59173264/114172812-da095980-993e-11eb-8257-abce9c6c3414.png)

I cannot apply any styles for iframe, could you please help ?
Add something like float: none or padding for versions above ? Thanks

**Comment by AaronAtDuo** [comment]
@nahaivla Unfortunately the CSS for the iframe is not easily modified, since it's being fetched from Duo.

We strongly recommend that applications migrate to our new Universal client.  This changes the prompt experience to allow for more control and customization.

There's some guidance on making the migration on our site at https://duo.com/docs/universal-prompt-update-guide
You can find the Java client here on Github at https://github.com/duosecurity/duo_universal_java, and it's also available on Maven

There's a step-by-step migration guide (in Python, but the idea is the same) at https://github.com/duosecurity/duo_python/pull/57

Thanks for using Duo!
