### ISSUE TITLE
Settings button in ie is not being displayed correctly.

### ISSUE THREAD

**Issue by sehgalsakshi** [duosecurity/duo_java#8]
The settings button overlaps on clicking any of the options for authentication. I tried increasing the height too but same behavior is repeated. 
Also the compatibility view is turned off, still no luck yet.
Here's the screenshot of the same: https://www.screencast.com/t/mX7ZZ3o973ln.
Hoping for a quick response.
Thank you!

**Comment by lgreerduo** [comment]
Hi, thanks for using Duo! 

What version of IE are you using and seeing this issue? We would like to replicate what you are seeing so we can help to get that resolved.

**Comment by sakshi22** [comment]
I'm using IE11

**Comment by AaronAtDuo** [comment]
Duo recommends migrating Java web applications to our new Universal Prompt flow.  Since it is not iframe based, there should be fewer CSS / layout issues.  It also will provide more options for customization in the coming months.

See https://duo.com/docs/universal-prompt-update-guide for more information on the new flow and how to migrate.

A client for Java that serves the same purpose as this repo is available at https://github.com/duosecurity/duo_universal_java and on Maven.

A demonstration of a step-by-step update to a simple Python web application can be seen at https://github.com/duosecurity/duo_python/pull/57 and should provide some guidance on the migration process.
